### ISSUE TITLE
Love it

### ISSUE THREAD

**Issue by Nekkok** [jptrzy/inventory-backpack-mod#1]
THANK YOU! Quark's backpack is the only one I could stand for; the other backpack's mods don't make any sense. How are you supposed to use a tool that's supposed to enhance your QoL if every time you need to access it you have to put it on the ground to open it? (talking about the rest of mods).

Anyway, will you add more feastures to it in the future? Trinket's compatibility is a must have, if you ask me (but you didn't). Anyway, thank you again so much for your nice addition to the game :D

**Comment by yesn0t** [comment]
@kxkxrxtx there's a fabric mod called quickshulkers (that improves more than just shulkers), it allows opening containers in the inventory using right click, and putting items into containers from inventory without opening them like bundles, very neat check it out.
Not necessarily as a replacement to this backpack mod but you know, as a complement to it and to other mods x)
sadly curseforge is the only place to download it at the moment, here u go https://www.curseforge.com/minecraft/mc-mods/quick-shulker

**Comment by jptrzy** [comment]
@kxkxrxtx I'm thinking about adding Trinket's compatibility and some small options for player choice. Thank you for your feedback.

**Comment by jptrzy** [comment]
In 0.2.0 release Trinket's compatibility has been added.

**Comment by yesn0t** [comment]
awesome ! looking forwards to it :D
