### ISSUE TITLE
Trinkets Configuration Option?

### ISSUE THREAD

**Issue by Bossfuratu** [jptrzy/inventory-backpack-mod#3]
Sorry if this is a waste of an issue submission, but is there a way to disable the Trinkets compatibility with the newest version? The private SMP server I run has to use Trinkets for Bewitchment, but I don't want my players to be able to use the Backpack in the Trinkets slot.

**Comment by jptrzy** [comment]
It's small change that I will add with options. Thanks again for your ideas.

**Comment by jptrzy** [comment]
I had added it to the code, but I will have to write more features to release it completely (and this could take some time).
