### ISSUE TITLE
Wearing off the backpack and putting it back causes problems with inventory updates

### ISSUE THREAD

**Issue by ppblitto** [jptrzy/inventory-backpack-mod#5]
> _Hello. First of all, this is a great and very userful mod and i'm loving it! Thank you for your effort! This kind of mod makes me hope that someday a version of Quark will be made for Fabric._

Well, I'm using this mod for a while now and I noticed two problems with inventory updates when I wear off the backpack and put it back. I'll explain them below:

- **Hand swap items doesn't happen until I open the inventory when I'm wearing a backpack.**
When I'm trying to put, say, torches in my off hand by pressing the F key, they don't go to the Off Hand slot until I press E to open the inventory. Only when the inventory screen is openned the torch appears in the slot. This happens every time.

- **Tools that break after their durability depletes doesn't disappear from the hotbar/inventory and the block doesnt break until I open the inventory when I'm wearing the backpack.**
This happens a lot when I'm mining with low tier tools like stone or iron. The tool won't go until I "update" the inventory by opening it. It's important to say that the durability progress bar does update, it's only when the tool breaks that the problem occurs.

I'm using the following inventory-related mods:

- Quick Shulker
- Shulker Box Tooltip
- Lenient Stack Sizes
- Mouse Tweaks
- Extra Sounds

And I tried to load the game without them to see if there was a compatibility issue with one or more of them, but no change. I tried adding one by one, but nothing as well.

**It seems like reentering in the word solves these problems, but it means that I'll have to be always with the backpack on me.**

I hope this feedback helps improving the mod. I really like it.

**Comment by jptrzy** [comment]
Thank you; I will look in it.

**Comment by jptrzy** [comment]
I have fixed it in 0.2.2 version.
