### ISSUE TITLE
takes over keybind of another mod

### ISSUE THREAD

**Issue by yesn0t** [jptrzy/inventory-backpack-mod#9]
hello, 
i ran into an issue, whenever i equip a backpack into trinket slot, with this mod installed https://modrinth.com/mod/extendedhotbarrebared  
and i press the keybind to swap hotbar slots (by default `R` , i changed it to different keys but same result), the inventory opens instead, as if i pressed `E` 
it's really strange and i'm not sure where to report it ^^' 

### steps to reproduce :
1) launch mc with extendedhotbarrebared and inventory backpack mod (and trinkets api)
2) equip a backpack into trinket slot
3) press `R` to swap slots between bottom and top hotbars

### actual result : 
* inventory GUI is opened

### expected result : 
* item is swapped to other hotbar

## details :  
* inventory backpack mod 0.2.2
* extendedhotbar 3.0.1
* trinkets 3.1.0
* fabric api 0.45.0
* fabric loader 0.12.12
* minecraft 1.18.1
* java 17

**Comment by jptrzy** [comment]
I will look into it.

**Comment by jptrzy** [comment]
Fix for it is in 0.2.3 version

**Comment by yesn0t** [comment]
thank you so much !
